// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.jason.mlsvconnx.proto;

/**
 * Protobuf type {@code model.ModelRequest}
 */
public final class ModelRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.ModelRequest)
    ModelRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ModelRequest.newBuilder() to construct.
  private ModelRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ModelRequest() {
    input1_ = emptyLongList();
    input2_ = emptyFloatList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ModelRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jason.mlsvconnx.proto.ModelOuterClass.internal_static_model_ModelRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jason.mlsvconnx.proto.ModelOuterClass.internal_static_model_ModelRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jason.mlsvconnx.proto.ModelRequest.class, com.jason.mlsvconnx.proto.ModelRequest.Builder.class);
  }

  public static final int INPUT1_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.LongList input1_;
  /**
   * <code>repeated int64 input1 = 1;</code>
   * @return A list containing the input1.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getInput1List() {
    return input1_;
  }
  /**
   * <code>repeated int64 input1 = 1;</code>
   * @return The count of input1.
   */
  public int getInput1Count() {
    return input1_.size();
  }
  /**
   * <code>repeated int64 input1 = 1;</code>
   * @param index The index of the element to return.
   * @return The input1 at the given index.
   */
  public long getInput1(int index) {
    return input1_.getLong(index);
  }
  private int input1MemoizedSerializedSize = -1;

  public static final int INPUT2_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.FloatList input2_;
  /**
   * <code>repeated float input2 = 2;</code>
   * @return A list containing the input2.
   */
  @java.lang.Override
  public java.util.List<java.lang.Float>
      getInput2List() {
    return input2_;
  }
  /**
   * <code>repeated float input2 = 2;</code>
   * @return The count of input2.
   */
  public int getInput2Count() {
    return input2_.size();
  }
  /**
   * <code>repeated float input2 = 2;</code>
   * @param index The index of the element to return.
   * @return The input2 at the given index.
   */
  public float getInput2(int index) {
    return input2_.getFloat(index);
  }
  private int input2MemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getInput1List().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(input1MemoizedSerializedSize);
    }
    for (int i = 0; i < input1_.size(); i++) {
      output.writeInt64NoTag(input1_.getLong(i));
    }
    if (getInput2List().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(input2MemoizedSerializedSize);
    }
    for (int i = 0; i < input2_.size(); i++) {
      output.writeFloatNoTag(input2_.getFloat(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < input1_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(input1_.getLong(i));
      }
      size += dataSize;
      if (!getInput1List().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      input1MemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      dataSize = 4 * getInput2List().size();
      size += dataSize;
      if (!getInput2List().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      input2MemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jason.mlsvconnx.proto.ModelRequest)) {
      return super.equals(obj);
    }
    com.jason.mlsvconnx.proto.ModelRequest other = (com.jason.mlsvconnx.proto.ModelRequest) obj;

    if (!getInput1List()
        .equals(other.getInput1List())) return false;
    if (!getInput2List()
        .equals(other.getInput2List())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getInput1Count() > 0) {
      hash = (37 * hash) + INPUT1_FIELD_NUMBER;
      hash = (53 * hash) + getInput1List().hashCode();
    }
    if (getInput2Count() > 0) {
      hash = (37 * hash) + INPUT2_FIELD_NUMBER;
      hash = (53 * hash) + getInput2List().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jason.mlsvconnx.proto.ModelRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jason.mlsvconnx.proto.ModelRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jason.mlsvconnx.proto.ModelRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jason.mlsvconnx.proto.ModelRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jason.mlsvconnx.proto.ModelRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jason.mlsvconnx.proto.ModelRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jason.mlsvconnx.proto.ModelRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jason.mlsvconnx.proto.ModelRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jason.mlsvconnx.proto.ModelRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jason.mlsvconnx.proto.ModelRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jason.mlsvconnx.proto.ModelRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jason.mlsvconnx.proto.ModelRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jason.mlsvconnx.proto.ModelRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.ModelRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.ModelRequest)
      com.jason.mlsvconnx.proto.ModelRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jason.mlsvconnx.proto.ModelOuterClass.internal_static_model_ModelRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jason.mlsvconnx.proto.ModelOuterClass.internal_static_model_ModelRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jason.mlsvconnx.proto.ModelRequest.class, com.jason.mlsvconnx.proto.ModelRequest.Builder.class);
    }

    // Construct using com.jason.mlsvconnx.proto.ModelRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      input1_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      input2_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jason.mlsvconnx.proto.ModelOuterClass.internal_static_model_ModelRequest_descriptor;
    }

    @java.lang.Override
    public com.jason.mlsvconnx.proto.ModelRequest getDefaultInstanceForType() {
      return com.jason.mlsvconnx.proto.ModelRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.jason.mlsvconnx.proto.ModelRequest build() {
      com.jason.mlsvconnx.proto.ModelRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.jason.mlsvconnx.proto.ModelRequest buildPartial() {
      com.jason.mlsvconnx.proto.ModelRequest result = new com.jason.mlsvconnx.proto.ModelRequest(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        input1_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.input1_ = input1_;
      if (((bitField0_ & 0x00000002) != 0)) {
        input2_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.input2_ = input2_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jason.mlsvconnx.proto.ModelRequest) {
        return mergeFrom((com.jason.mlsvconnx.proto.ModelRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jason.mlsvconnx.proto.ModelRequest other) {
      if (other == com.jason.mlsvconnx.proto.ModelRequest.getDefaultInstance()) return this;
      if (!other.input1_.isEmpty()) {
        if (input1_.isEmpty()) {
          input1_ = other.input1_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureInput1IsMutable();
          input1_.addAll(other.input1_);
        }
        onChanged();
      }
      if (!other.input2_.isEmpty()) {
        if (input2_.isEmpty()) {
          input2_ = other.input2_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureInput2IsMutable();
          input2_.addAll(other.input2_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              long v = input.readInt64();
              ensureInput1IsMutable();
              input1_.addLong(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureInput1IsMutable();
              while (input.getBytesUntilLimit() > 0) {
                input1_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            } // case 10
            case 21: {
              float v = input.readFloat();
              ensureInput2IsMutable();
              input2_.addFloat(v);
              break;
            } // case 21
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureInput2IsMutable();
              while (input.getBytesUntilLimit() > 0) {
                input2_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.LongList input1_ = emptyLongList();
    private void ensureInput1IsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        input1_ = mutableCopy(input1_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int64 input1 = 1;</code>
     * @return A list containing the input1.
     */
    public java.util.List<java.lang.Long>
        getInput1List() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(input1_) : input1_;
    }
    /**
     * <code>repeated int64 input1 = 1;</code>
     * @return The count of input1.
     */
    public int getInput1Count() {
      return input1_.size();
    }
    /**
     * <code>repeated int64 input1 = 1;</code>
     * @param index The index of the element to return.
     * @return The input1 at the given index.
     */
    public long getInput1(int index) {
      return input1_.getLong(index);
    }
    /**
     * <code>repeated int64 input1 = 1;</code>
     * @param index The index to set the value at.
     * @param value The input1 to set.
     * @return This builder for chaining.
     */
    public Builder setInput1(
        int index, long value) {
      ensureInput1IsMutable();
      input1_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 input1 = 1;</code>
     * @param value The input1 to add.
     * @return This builder for chaining.
     */
    public Builder addInput1(long value) {
      ensureInput1IsMutable();
      input1_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 input1 = 1;</code>
     * @param values The input1 to add.
     * @return This builder for chaining.
     */
    public Builder addAllInput1(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureInput1IsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, input1_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 input1 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearInput1() {
      input1_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.FloatList input2_ = emptyFloatList();
    private void ensureInput2IsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        input2_ = mutableCopy(input2_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated float input2 = 2;</code>
     * @return A list containing the input2.
     */
    public java.util.List<java.lang.Float>
        getInput2List() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(input2_) : input2_;
    }
    /**
     * <code>repeated float input2 = 2;</code>
     * @return The count of input2.
     */
    public int getInput2Count() {
      return input2_.size();
    }
    /**
     * <code>repeated float input2 = 2;</code>
     * @param index The index of the element to return.
     * @return The input2 at the given index.
     */
    public float getInput2(int index) {
      return input2_.getFloat(index);
    }
    /**
     * <code>repeated float input2 = 2;</code>
     * @param index The index to set the value at.
     * @param value The input2 to set.
     * @return This builder for chaining.
     */
    public Builder setInput2(
        int index, float value) {
      ensureInput2IsMutable();
      input2_.setFloat(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float input2 = 2;</code>
     * @param value The input2 to add.
     * @return This builder for chaining.
     */
    public Builder addInput2(float value) {
      ensureInput2IsMutable();
      input2_.addFloat(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float input2 = 2;</code>
     * @param values The input2 to add.
     * @return This builder for chaining.
     */
    public Builder addAllInput2(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureInput2IsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, input2_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float input2 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInput2() {
      input2_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.ModelRequest)
  }

  // @@protoc_insertion_point(class_scope:model.ModelRequest)
  private static final com.jason.mlsvconnx.proto.ModelRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jason.mlsvconnx.proto.ModelRequest();
  }

  public static com.jason.mlsvconnx.proto.ModelRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ModelRequest>
      PARSER = new com.google.protobuf.AbstractParser<ModelRequest>() {
    @java.lang.Override
    public ModelRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ModelRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ModelRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.jason.mlsvconnx.proto.ModelRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

