// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.jason.mlsvconnx.proto;

public final class ModelOuterClass {
  private ModelOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_ModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_ModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_ModelReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_ModelReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013model.proto\022\005model\".\n\014ModelRequest\022\016\n\006" +
      "input1\030\001 \003(\003\022\016\n\006input2\030\002 \003(\002\"\034\n\nModelRep" +
      "ly\022\016\n\006output\030\001 \003(\0022=\n\005Model\0224\n\010RunModel\022" +
      "\023.model.ModelRequest\032\021.model.ModelReply\"" +
      "\000B\035\n\031com.jason.mlsvconnx.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_model_ModelRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_ModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_ModelRequest_descriptor,
        new java.lang.String[] { "Input1", "Input2", });
    internal_static_model_ModelReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_ModelReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_ModelReply_descriptor,
        new java.lang.String[] { "Output", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
