// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.jason.mlsvconnx.proto;

/**
 * Protobuf type {@code model.ModelReply}
 */
public final class ModelReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.ModelReply)
    ModelReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ModelReply.newBuilder() to construct.
  private ModelReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ModelReply() {
    output_ = emptyFloatList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ModelReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jason.mlsvconnx.proto.ModelOuterClass.internal_static_model_ModelReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jason.mlsvconnx.proto.ModelOuterClass.internal_static_model_ModelReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jason.mlsvconnx.proto.ModelReply.class, com.jason.mlsvconnx.proto.ModelReply.Builder.class);
  }

  public static final int OUTPUT_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.FloatList output_;
  /**
   * <code>repeated float output = 1;</code>
   * @return A list containing the output.
   */
  @java.lang.Override
  public java.util.List<java.lang.Float>
      getOutputList() {
    return output_;
  }
  /**
   * <code>repeated float output = 1;</code>
   * @return The count of output.
   */
  public int getOutputCount() {
    return output_.size();
  }
  /**
   * <code>repeated float output = 1;</code>
   * @param index The index of the element to return.
   * @return The output at the given index.
   */
  public float getOutput(int index) {
    return output_.getFloat(index);
  }
  private int outputMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getOutputList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(outputMemoizedSerializedSize);
    }
    for (int i = 0; i < output_.size(); i++) {
      output.writeFloatNoTag(output_.getFloat(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      dataSize = 4 * getOutputList().size();
      size += dataSize;
      if (!getOutputList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      outputMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jason.mlsvconnx.proto.ModelReply)) {
      return super.equals(obj);
    }
    com.jason.mlsvconnx.proto.ModelReply other = (com.jason.mlsvconnx.proto.ModelReply) obj;

    if (!getOutputList()
        .equals(other.getOutputList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOutputCount() > 0) {
      hash = (37 * hash) + OUTPUT_FIELD_NUMBER;
      hash = (53 * hash) + getOutputList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jason.mlsvconnx.proto.ModelReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jason.mlsvconnx.proto.ModelReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jason.mlsvconnx.proto.ModelReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jason.mlsvconnx.proto.ModelReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jason.mlsvconnx.proto.ModelReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jason.mlsvconnx.proto.ModelReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jason.mlsvconnx.proto.ModelReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jason.mlsvconnx.proto.ModelReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jason.mlsvconnx.proto.ModelReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jason.mlsvconnx.proto.ModelReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jason.mlsvconnx.proto.ModelReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jason.mlsvconnx.proto.ModelReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jason.mlsvconnx.proto.ModelReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.ModelReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.ModelReply)
      com.jason.mlsvconnx.proto.ModelReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jason.mlsvconnx.proto.ModelOuterClass.internal_static_model_ModelReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jason.mlsvconnx.proto.ModelOuterClass.internal_static_model_ModelReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jason.mlsvconnx.proto.ModelReply.class, com.jason.mlsvconnx.proto.ModelReply.Builder.class);
    }

    // Construct using com.jason.mlsvconnx.proto.ModelReply.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      output_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jason.mlsvconnx.proto.ModelOuterClass.internal_static_model_ModelReply_descriptor;
    }

    @java.lang.Override
    public com.jason.mlsvconnx.proto.ModelReply getDefaultInstanceForType() {
      return com.jason.mlsvconnx.proto.ModelReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.jason.mlsvconnx.proto.ModelReply build() {
      com.jason.mlsvconnx.proto.ModelReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.jason.mlsvconnx.proto.ModelReply buildPartial() {
      com.jason.mlsvconnx.proto.ModelReply result = new com.jason.mlsvconnx.proto.ModelReply(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        output_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.output_ = output_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jason.mlsvconnx.proto.ModelReply) {
        return mergeFrom((com.jason.mlsvconnx.proto.ModelReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jason.mlsvconnx.proto.ModelReply other) {
      if (other == com.jason.mlsvconnx.proto.ModelReply.getDefaultInstance()) return this;
      if (!other.output_.isEmpty()) {
        if (output_.isEmpty()) {
          output_ = other.output_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureOutputIsMutable();
          output_.addAll(other.output_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              float v = input.readFloat();
              ensureOutputIsMutable();
              output_.addFloat(v);
              break;
            } // case 13
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureOutputIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                output_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.FloatList output_ = emptyFloatList();
    private void ensureOutputIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        output_ = mutableCopy(output_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated float output = 1;</code>
     * @return A list containing the output.
     */
    public java.util.List<java.lang.Float>
        getOutputList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(output_) : output_;
    }
    /**
     * <code>repeated float output = 1;</code>
     * @return The count of output.
     */
    public int getOutputCount() {
      return output_.size();
    }
    /**
     * <code>repeated float output = 1;</code>
     * @param index The index of the element to return.
     * @return The output at the given index.
     */
    public float getOutput(int index) {
      return output_.getFloat(index);
    }
    /**
     * <code>repeated float output = 1;</code>
     * @param index The index to set the value at.
     * @param value The output to set.
     * @return This builder for chaining.
     */
    public Builder setOutput(
        int index, float value) {
      ensureOutputIsMutable();
      output_.setFloat(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float output = 1;</code>
     * @param value The output to add.
     * @return This builder for chaining.
     */
    public Builder addOutput(float value) {
      ensureOutputIsMutable();
      output_.addFloat(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float output = 1;</code>
     * @param values The output to add.
     * @return This builder for chaining.
     */
    public Builder addAllOutput(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureOutputIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, output_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float output = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutput() {
      output_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.ModelReply)
  }

  // @@protoc_insertion_point(class_scope:model.ModelReply)
  private static final com.jason.mlsvconnx.proto.ModelReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jason.mlsvconnx.proto.ModelReply();
  }

  public static com.jason.mlsvconnx.proto.ModelReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ModelReply>
      PARSER = new com.google.protobuf.AbstractParser<ModelReply>() {
    @java.lang.Override
    public ModelReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ModelReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ModelReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.jason.mlsvconnx.proto.ModelReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

