// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.jason.mlsvconnx.proto;

public interface ModelReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.ModelReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated float output = 1;</code>
   * @return A list containing the output.
   */
  java.util.List<java.lang.Float> getOutputList();
  /**
   * <code>repeated float output = 1;</code>
   * @return The count of output.
   */
  int getOutputCount();
  /**
   * <code>repeated float output = 1;</code>
   * @param index The index of the element to return.
   * @return The output at the given index.
   */
  float getOutput(int index);
}
