// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.jason.mlsvconnx.proto;

public interface ModelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.ModelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 input1 = 1;</code>
   * @return A list containing the input1.
   */
  java.util.List<java.lang.Long> getInput1List();
  /**
   * <code>repeated int64 input1 = 1;</code>
   * @return The count of input1.
   */
  int getInput1Count();
  /**
   * <code>repeated int64 input1 = 1;</code>
   * @param index The index of the element to return.
   * @return The input1 at the given index.
   */
  long getInput1(int index);

  /**
   * <code>repeated float input2 = 2;</code>
   * @return A list containing the input2.
   */
  java.util.List<java.lang.Float> getInput2List();
  /**
   * <code>repeated float input2 = 2;</code>
   * @return The count of input2.
   */
  int getInput2Count();
  /**
   * <code>repeated float input2 = 2;</code>
   * @param index The index of the element to return.
   * @return The input2 at the given index.
   */
  float getInput2(int index);
}
